[Feature/main] 메인 페이지 레이아웃 및 기능 완료
p-acid/nextlevel-assignment pull request #2
Opened 2022-01-07 05:42 UTC by p-acid

# 구현 사항

- 메인 페이지에 해당하는 `index` 페이지 제작
  - 토큰을 활용한 `userData` 요청
    - 기존에 작성했던 `localStorage` 저장 방식에서 `cookie` 저장 방식으로 전환
  - 쿼리스트링을 통한 데이터 분할 요청
    - 페이지네이션 방식으로
  - `Header` 영역 로그아웃 기능 추가

<br/>

#  구현 화면

![pixel-assignment](https://user-images.githubusercontent.com/87939521/148496894-559f573e-0796-4cbf-89ae-3af45ebcdfad.gif)
</br>

# 학습 내용

- SSR에서의 토큰 관리 방식
- 페이지네이션 구현 방식

2022-01-07 08:10 UTC, heejinlee07 reviewed
고생많으셨습니다😀  이따 한 번 올라가서 전달드릴 내용이 있으니 아직 추가 수정 작업하지 마세요:)

2022-01-07 08:10 UTC, heejinlee07 commented on components/PageBtns/PageBtns.tsx
> +  const currentPage = currentStart / 5 + 1;
P1: 이 수식의 정체는 무엇인가요? 수식을 표현할 때 지금처럼 5 + 1로 나타나게 되면 의도를 알 수 없습니다. 이런 것들은 매직넘버로 빼서 관리하도록 해주세요

매직넘버 예시: https://drehzr.tistory.com/1136

2022-01-07 08:10 UTC, heejinlee07 commented on components/PageBtns/PageBtns.tsx
> +                  </svg>
P1: 삼항연산자를 이렇게 길게 구현하지 마세요. 가독성이 떨어집니다

2022-01-11 03:33 UTC, p-acid commented on components/List/List.tsx
> +interface ListI {
### 리뷰 답장
---
- 인터페이스를 의미하는 `I` 지만 의미가 불명확하다는 말씀에 동의하여 수정 진행하였습니다!
- `ListI` => `ListInterface`

2022-01-11 07:10 UTC, heejinlee07 commented on pages/index.tsx
> +      res => {
P1 : res에 대한 type 지정해주세요!

2022-01-11 07:12 UTC, heejinlee07 commented on pages/index.tsx
> +        setContentList([...list]);
P3: setContentList에 res.data 바로 적용하면 되지 않나요? 이렇게 작성하신 이유가 궁금합니다

2022-01-11 07:36 UTC, heejinlee07 approved these changes
고생많으셨습니다! 정말..사무엘이 생각하기에도 코드가 정말 깔끔해지지 않았나요???
정말 너무 가독성 있고 좋습니다 굿굿

저의 지금 기분👇
![image](https://user-images.githubusercontent.com/56146465/148900288-097db4dd-e535-4cf0-ad64-39d6805785b8.png)

2022-01-11 07:57 UTC, p-acid commented on pages/index.tsx
> +        setContentList([...list]);
### 리뷰 답장
---
타입스크립트에 대한 이해가 충분치 않아 울며 겨자먹기식으로 해결한 것 같습니다...! 다시금 어느 정도 이해한 방향으로 수정 진행하였습니다!

2022-01-11 07:59 UTC, p-acid commented
갓갓 클레어 덕분입니다... 외쳐 갓레어 🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌🙌

2022-01-11 08:27 UTC, heejinlee07 commented
이번 PR은 특별히 Lotto(@Lissu-FE)도 봐주실 겁니다 Lotto pr까지 마무리되면 그때 확인 후 머지시켜주세요

2022-01-12 01:42 UTC, Lissu-FE requested changes
고생하셨습니다!!

- 토큰값을 다 지운 상태로 메인 페이지 접근시 로그인페이지로 튕겨내지 않습니다.(토큰이 있다면 로그인페이지로 접근했을때 홈으로 보내는것도 같이 확인해주세요!)

2022-01-12 01:52 UTC, p-acid commented on components/Banner/Banner.tsx
> +            <Tag key={idx}>#{tagName}</Tag>
### 리뷰 답장
---
좋은 리뷰 감사합니다! 수정 진행하겠습니다.

부가적으로 질문이 하나 있는데, `key` 라는 prop는 렌더링 되는 뷰 내의 모든 요소들에서 고유한 요소여야 한다고 이해하면 되는 걸까요? 아니면 함께 `map` 을 순환하는 요소들 사이에서만 고유한 요소이면 될까요?

2022-01-12 03:04 UTC, p-acid commented on components/Banner/BannerStyle.tsx
> +export const Tag = styled.li``;
### 리뷰 답장
---
CSS 내용이 누락되었던 것 같습니다! 수정 진행하겠습니다

2022-01-12 03:59 UTC, Lissu-FE commented on components/Banner/Banner.tsx
> +            <Tag key={idx}>#{tagName}</Tag>
Key는 배열 안에서 형제 사이에서 고유해야 하고 전체 범위에서 고유할 필요는 없습니다. 두 개의 다른 배열을 만들 때 동일한 key를 사용할 수 있습니다.

https://ko.reactjs.org/docs/lists-and-keys.html
이부분을 확인해보면 좋을것같아요!

2022-01-12 05:24 UTC, Lissu-FE approved these changes
고생하셨습니다~!!

로그인 토큰이 있는 상태에서 주소창으로 sign-in을 접근할때 홈으로 보내주거나, 토큰을 지우는 작업만 추가해서 머지 해주세요!!😀

2022-01-12 05:42 UTC, p-acid commented
토큰 제거하는 것으로 마무리 지었습니다. 감사합니다!

2022-01-12 05:42 UTC, merged